/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('/ring.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Camera" position={[0, 0, 0]} rotation={[0, 0, 0]}>
        <PerspectiveCamera fov={20} near={0.1} far={100} />
      </group>
      <group name="Sun" position={[1000, 500, 1000]} rotation={[-Math.PI / 2, 0, 0]}>
        <pointLight intensity={10} />
      </group>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} scale={[200, 200, 200]}>
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} scale={[200, 200, 200]} >
        <meshPhongMaterial color="rgb(255,215,0)" />
      </mesh>
      <mesh
        geometry={nodes.Diamond_Round.geometry}
        material={nodes.Diamond_Round.material}
        position={[0, 0, 2.8]}
        scale={[100, 100, 100]}
      />
    </group>
  )
}

useGLTF.preload('/ring.glb')
